services:
  app:
    build: .
    container_name: my_app
    environment:
      - HF_TOKEN=${HF_TOKEN}
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped